# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk15

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  # - bash <(curl -s https://codecov.io/bash)

env:
  global:
      - CODECOV_TOKEN='3bf80890-b3f5-43e8-a0af-c4d47ff3e0cd'

# Отправлять уведомление на почту sergioparovozov@gmail.com (Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      - sergioparovozov@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
